"""adding transcription_saved model

Revision ID: a9dc4be1a8a4
Revises: 
Create Date: 2019-04-11 18:58:52.658471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dc4be1a8a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcription', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcription_saved',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audio_path', sa.String(length=120), nullable=True),
    sa.Column('transcription', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcription_saved')
    op.drop_table('transcription')
    # ### end Alembic commands ###
